server:
  port: 8501

spring:
  application:
    name: service-cloud-consummer
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: mysql123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


